version: 0.0
os: linux
files:
- source: "/"
  destination: "/home/ec2-user/cdk/"
hooks:
  AfterInstall:
  - location: "assets/devopsIaC/bootstrap.sh"
    timeout: 300
    runas: ec2-user
  ApplicationStart:
  - location: "assets/devopsIaC/deploy.sh"
    timeout: 900
    runas: ec2-user   
  ApplicationStop:
  - location: "assets/devopsIaC/stop.sh"
    timeout: 600
    runas: ec2-user   