---

- name: "Create User {{ item.username }}"
  shell:
    cmd: |
      aws identitystore create-user --identity-store-id={{ aws_iam_ic_idstore_id.stdout }}  --user-name="{{ item.username }}" --display-name="{{ item.firstname }} {{ item.lastname }}" --name='{"FamilyName": "{{ item.lastname }}","GivenName": "{{ item.firstname }}"}' --email='[{"Value": "{{ item.email }}","Type": "Work.","Primary": true}]' | grep UserId | cut -d ' ' -f 6 | sed -r "s/\"//g" | sed -r "s/,//g"
  register: results_user_created
  failed_when: "(results_user_created.stdout != '') and (results_user_created.rc != 0)"
  changed_when: "results_user_created.stdout != ''"

- name: "Determine group id for {{ item.username }}" 
  shell:
    cmd: |
      aws identitystore list-groups --identity-store-id='{{ aws_iam_ic_idstore_id.stdout }}' | grep -E "DisplayName|GroupId" | awk 'NR%2{printf "%s ",$0;next;}1' | grep "{{ item.group }}\"" | cut -d ',' -f 1 | cut -d ':' -f2 | sed -r "s/\"//g" | sed -r "s/,//g"  | sed -r "s/ //g"
  register: results_group_id
  changed_when: false
  when: "results_user_created.changed"

- name: "Add User {{ item.username }} to group {{ item.group }}"
  shell:
    cmd: |
      aws identitystore create-group-membership --identity-store-id='{{ aws_iam_ic_idstore_id.stdout }}' --group-id='{{ results_group_id.stdout  }}' --member-id='{"UserId": "{{ results_user_created.stdout }}"}'
  when: "results_user_created.changed"