---

- name: Get Permission Set for Group
  shell:
    cmd: |
      bash ~/iam_ic_permissionset.sh | grep {{ item.permissionset }} | cut -d ',' -f2 | cut -d ' ' -f 11 | sed -r "s/\"//g" | sed -r "s/,//g"
  register: results_permissionset_arn
  changed_when: false

- name: Get Group Id
  shell:
    cmd: |
      aws identitystore list-groups --identity-store-id='{{ aws_iam_ic_idstore_id.stdout }}' | grep -E "DisplayName|GroupId" | awk 'NR%2{printf "%s ",$0;next;}1' | grep "{{ item.name }}\"" | cut -d ',' -f 1 | cut -d ':' -f2 | sed -r "s/\"//g" | sed -r "s/,//g"  | sed -r "s/ //g"
  register: results_group_id
  changed_when: false

- name: Bind Permission Set to Account
  shell:
    cmd: |
      aws sso-admin create-account-assignment --instance-arn="{{ aws_iam_ic_arn.stdout }}" --permission-set-arn="{{ results_permissionset_arn.stdout }}" --target-id="{{ item.account_id }}" --target-type=AWS_ACCOUNT --principal-id="{{ results_group_id.stdout }}" --principal-type=GROUP